// This file was auto-generated by FlutterFire CLI but is not used in this project.
// The project uses Supabase for backend services instead.
// It is kept for reference in case Firebase is needed in the future.
// 
// To regenerate this file with Firebase support, run:
//   flutterfire configure

